version: "3"

networks:
  monitoring:

services:
  alertmanager:
    image: axus/alertmanager:latest
    networks:
      - monitoring
    ports:
     - "9093:9093"
    command: -config.file=/etc/alertmanager/config.yml
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.01'
          memory: 32M
        reservations:
          cpus: '0.01'
          memory: 16M

  prometheus:
    image: gitlab.sanookonline.co.th:9443/itinfra/docker-prometheus-swarm:latest
    ports:
      - "9090:9090"
    networks:
      - monitoring
    command: -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles -alertmanager.url=http://alertmanager:9093
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 128M

  alerta:
    image: axus/alert-broker:latest
    networks:
      - monitoring
    deploy:
      mode: replicated
      replicas: 1