global:
  scrape_interval:     30s
  evaluation_interval: 30s

  #labels:
  #  cluster: swarm
  #  replica: "1"

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-swarm'

rule_files:
  - "alert.rules_nodes"
  - "alert.rules_tasks"
  - "alert.rules_service-groups"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'docker-targets'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets.json'
